name: uwifiapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.3.1
  chewie: ^1.7.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_card_swiper: ^7.0.2
  formz: ^0.7.0
  get_it: ^8.0.0
  internet_connection_checker: ^3.0.1
  local_auth: ^2.2.0
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2
  shared_preferences: ^2.3.2
  sleek_circular_slider: ^2.1.0
  supabase_flutter: ^2.8.0
  url_launcher: ^6.2.5
  video_player: ^2.8.2

dev_dependencies:

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/homeimage/
    - assets/images/login/
    - assets/images/profile/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
